services:
  quatrobus:
    container_name: instance-quatrobus
    build: 
      context: ./instance-quatrobus/
      dockerfile: Dockerfile
    volumes:
      - /var/www/mcets/instance-quatrobus:/var/www
    networks:
      - mcets-quatrobus-db-net
      - mcets-api
      - revert-proxy
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 280510jt
    ports:
      - 33060:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mcets-quatrobus-db-net
  web:
    container_name: instance-web
    build: 
      context: ./instance-web/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - /var/www/mcets/instance-web:/var/www
    networks:
      - mcets-api
      - revert-proxy
      - mcets-web-redis-net
    depends_on:
      - redis
  monitor:
    container_name: instance-qmonitor
    build:
      context: ./instance-qmonitor/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - 5173:5173
    volumes:
      - /var/www/mcets/instance-qmonitor:/var/www
    networks:
      - mcets-api
      - revert-proxy
      - mcets-quatrobus-db-net
    depends_on:
      - mariadb
  nginx:
    container_name: nginx
    build: 
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
    - NGINX_PORT=80
    - DOMINIO_QUATROBUS=quatrobus
    - SERVICIO_QUATROBUS=quatrobus:80
    - DOMINIO_QUAWEB=quaweb.phalcon
    - SERVICIO_WEB=web:80
    networks:
      - revert-proxy
    depends_on:
      - quatrobus
      - web
  redis:
    image: redis:4.0.9
    command: ["redis-server", "--requirepass", "globalbts"]
    ports:
      - 63790:6379
    networks:
      - mcets-web-redis-net
networks:
  mcets-quatrobus-db-net:
    driver: bridge    
  mcets-api:
    driver: bridge    
  revert-proxy:
    driver: bridge    
  mcets-web-redis-net:
    driver: bridge
volumes:
  mariadb_data: