services:
  quatrobus:
    container_name: instance-quatrobus
    build: 
      context: ./instance-quatrobus/
      dockerfile: Dockerfile
    volumes:
      - /var/www/mcets/instance-quatrobus:/var/www
    networks:
      - mcets-quatrobus-db-net
      - mcets-api
      - revert-proxy
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 280510jt
    ports:
      - 33060:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mcets-quatrobus-db-net
  # web:
  #   container_name: instance-web
  #   build: 
  #     context: ./instance-web/
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - /var/www/mcets/instance-web:/var/www
  #   networks:
  #     - mcets-api
  #     - revert-proxy
  nginx:
    container_name: nginx
    build: 
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
    - NGINX_PORT=80
    - DOMINIO_QUATROBUS=quatrobus
    - SERVICIO_QUATROBUS=quatrobus:80
    - DOMINIO2=quaweb.phalcon
    - SERVICIO2=web:80
    networks:
      - revert-proxy
    depends_on:
      - quatrobus
      # - web
networks:
  mcets-quatrobus-db-net:
    driver: bridge    
  mcets-api:
    driver: bridge    
  revert-proxy:
    driver: bridge    
volumes:
  mariadb_data: