services:
  quatrobus:
    container_name: instance-quatrobus
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "85:80"
    volumes:
      - /var/www/mcets/instance-quatrobus:/var/www
